### ISSUE TITLE
Error on run build task in VSCode

### ISSUE THREAD

**Issue by thamiris-ramos** [GeneralBots/BotServer#112]
**Describe the bug**
When run build task in VSCode occurs the folowing error, despite the build run succesfuly:
Error: The typescript task detection didn't contribute a task for the following configuration:
{
    "type": "typescript",
    "tsconfig": "tsconfig.json",
    "option": "watch",
    "problemMatcher": [
        "$tsc-watch"
    ],
    "group": {
        "kind": "build",
        "isDefault": true
    }
}
The task will be ignored.

**To Reproduce**
1. Ctrl + B
2. Run tscwatch [BotServer path]

**Expected behavior**
Build without errors

**Comment by rodrigorodriguez** [comment]
Working in current version.
