### ISSUE TITLE
Keyword - Basic - "menu"

### ISSUE THREAD

**Issue by PH-Nascimento** [GeneralBots/BotServer#138]
Dinânimca de menus e submenus
Permitir navegação entre menus e submenus reativando a hierarquia do gbkb.

**Comment by rodrigorodriguez** [comment]
Check this:
https://github.com/GeneralBots/BotBook/blob/master/book/chapter-05-gbdialog-reference.md

![image](https://user-images.githubusercontent.com/14840374/131328336-254309e6-6e7c-41a2-b8ba-60cec1369bf5.png)
