### ISSUE TITLE
SET SCHEDULE BASIC KEYWORD

### ISSUE THREAD

**Issue by rodrigorodriguez** [GeneralBots/BotServer#166]
pt-br: Permitir o agendamento de processos como disparos periódicos.

set schedule "42 * * * *"
find = "diario.pdf" 
talk to 
send email

References:

https://www.npmjs.com/package/node-schedule
Cron-style Scheduling
The cron format consists of:

*    *    *    *    *    *
┬    ┬    ┬    ┬    ┬    ┬
│    │    │    │    │    │
│    │    │    │    │    └ day of week (0 - 7) (0 or 7 is Sun)
│    │    │    │    └───── month (1 - 12)
│    │    │    └────────── day of month (1 - 31)
│    │    └─────────────── hour (0 - 23)
│    └──────────────────── minute (0 - 59)
└───────────────────────── second (0 - 59, OPTIONAL)

**Comment by PH-Nascimento** [comment]
@rodrigorodriguez necessário script para realização do teste.
