### ISSUE TITLE
Create hear as qrcode

### ISSUE THREAD

**Issue by PH-Nascimento** [GeneralBots/BotServer#171]
Bot recebe imagem de qrcode e executa a ação correspondente.
De modo que a pessoa possa realizar a captura da imagem recebida pelo Bot.
Exemplo: Cliente seleciona produto e realiza pedido. Empresa recebe pedido e gera QRCode de pagamento correspondente e envia para o Bot que envia a imagem ao cliente. O celular do cliente precisa capturar o QRCode para concluir o pagamento.

**Comment by rodrigorodriguez** [comment]
https://www.npmjs.com/package/qr-scanner
