### ISSUE TITLE
Opções de menu no 'hear as' está limitado a 3 itens

### ISSUE THREAD

**Issue by PH-Nascimento** [GeneralBots/BotServer#266]
A palavra chave que admite apresentar as opções em botões do WhatsApp está limitada a apenas 3 itens.

**Comment by rodrigorodriguez** [comment]
whatsapp-web.js e puppeteer

**Comment by rodrigorodriguez** [comment]
https://github.com/pedroslopez/whatsapp-web.js/issues/1938#issuecomment-1397982452

**Comment by rodrigorodriguez** [comment]
https://github.com/GeneralBots/BotServer/issues/288
