### ISSUE TITLE
Botões do WhatsApp inativos

### ISSUE THREAD

**Issue by rodrigorodriguez** [GeneralBots/BotServer#288]

**Comment by PH-Nascimento** [comment]
Botões só funcionam no WhatsApp Web.
Pelo celular eles não aparecem.
**Celular**:

![image](https://user-images.githubusercontent.com/42078703/229296973-ea7229f2-0dca-4489-a9c0-c04f76942742.png)

**WhatsApp Web:**

![image](https://user-images.githubusercontent.com/42078703/229296996-4050706e-6cf3-4428-8f17-04889c3a8187.png)
