### ISSUE TITLE
Review debugger BASIC to JS map generation

### ISSUE THREAD

**Issue by AlanPerdomo** [GeneralBots/BotServer#326]

**Comment by AlanPerdomo** [comment]
![image](https://user-images.githubusercontent.com/18701256/214879398-77b27925-df4d-435c-bc98-022dfb87b9eb.png)

**Comment by rodrigorodriguez** [comment]
https://github.com/GeneralBots/BotServer/commit/3d6bc56eca84542483dcb41c93b3f7bafb890dc6

**Comment by rodrigorodriguez** [comment]
![image](https://user-images.githubusercontent.com/14840374/215353638-4a26e452-d30f-453c-aa9a-c479c5bc6b6d.png)
