### ISSUE TITLE
VM error, out of memory.

### ISSUE THREAD

**Issue by AlanPerdomo** [GeneralBots/BotServer#340]
20230322T110817 GB error WhatsApp API lost connection for: GeneralBots001.

<--- Last few GCs --->

[5106:0x5599c289be90] 215910986 ms: Scavenge 1921.7 (1995.0) -> 1917.1 (1995.0) MB, 6.8 / 0.2 ms  (average mu = 0.949, current mu = 0.950) task; 
[5106:0x5599c289be90] 215914935 ms: Scavenge 1923.3 (1995.3) -> 1918.6 (1995.3) MB, 7.7 / 0.2 ms  (average mu = 0.949, current mu = 0.950) task; 
[5106:0x5599c289be90] 215918090 ms: Scavenge 1924.2 (1995.3) -> 1919.6 (2011.3) MB, 10.9 / 0.1 ms  (average mu = 0.949, current mu = 0.950) task; 

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x7f3b2c9f103c node::Abort() [/lib/x86_64-linux-gnu/libnode.so.108]
 2: 0x7f3b2c8e72f8  [/lib/x86_64-linux-gnu/libnode.so.108]
 3: 0x7f3b2cd6207a v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.108]
 4: 0x7f3b2cd62437 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/lib/x86_64-linux-gnu/libnode.so.108]
 5: 0x7f3b2cf4af19  [/lib/x86_64-linux-gnu/libnode.so.108]
 6: 0x7f3b2cf610e3 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/lib/x86_64-linux-gnu/libnode.so.108]
 7: 0x7f3b2cfdcb5c v8::internal::ScavengeJob::Task::RunInternal() [/lib/x86_64-linux-gnu/libnode.so.108]
 8: 0x7f3b2ca6ffa0 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [/lib/x86_64-linux-gnu/libnode.so.108]
 9: 0x7f3b2ca70dc2 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [/lib/x86_64-linux-gnu/libnode.so.108]
10: 0x7f3b2ee1332d  [/lib/x86_64-linux-gnu/libuv.so.1]
11: 0x7f3b2ee2ee6d  [/lib/x86_64-linux-gnu/libuv.so.1]
12: 0x7f3b2ee18dba uv_run [/lib/x86_64-linux-gnu/libuv.so.1]
13: 0x7f3b2c91d206 node::SpinEventLoop(node::Environment*) [/lib/x86_64-linux-gnu/libnode.so.108]
14: 0x7f3b2ca3cb33 node::NodeMainInstance::Run(int*, node::Environment*) [/lib/x86_64-linux-gnu/libnode.so.108]
15: 0x7f3b2ca3cfba node::NodeMainInstance::Run() [/lib/x86_64-linux-gnu/libnode.so.108]
16: 0x7f3b2c9b3c10 node::Start(int, char**) [/lib/x86_64-linux-gnu/libnode.so.108]
17: 0x7f3b2bc23510  [/lib/x86_64-linux-gnu/libc.so.6]
18: 0x7f3b2bc235c9 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
19: 0x5599c20be0f5 _start [node]
Aborted (core dumped)

**Comment by rodrigorodriguez** [comment]
https://learn.microsoft.com/en-us/troubleshoot/azure/virtual-machines/oom-swap-file-linux-vm

export NODE_OPTIONS=--max-old-space-size=4096
