### ISSUE TITLE
Use SET with filter

### ISSUE THREAD

**Issue by PH-Nascimento** [GeneralBots/BotServer#344]
O comando SET quando usado a cada resposta, como no RecrutaBot, acaba salvando na linha errada se no mesmo instante alguém estiver inserindo uma nova linha... então o que era B32 passa a ser B33. Mas, como o FIND que localizou a linha aconteceu lá no começo do dialog, tive que incluir um FIND a cada resposta. 
Considerando que deve ser uma coisa recorrente em muitos Bots (terem acessos simultâneos), vamos precisar encontrar uma forma de evitar esse problema (que pode bagunçar as tabelas do gbdata).

SET "file.xlsx", "A1=39349", "B1", 800

**Comment by rodrigorodriguez** [comment]
SET FILTER "ID=1112"
SET "file.xlsx", "A", "Value"

**Comment by PH-Nascimento** [comment]
**Log:**
![image](https://user-images.githubusercontent.com/42078703/229360794-4aa5ea98-0c08-42dd-bc0c-20e9977daff6.png)

**Dialog acatatask:**
![image](https://user-images.githubusercontent.com/42078703/229360883-9f104f81-c715-4342-af8b-f8cad3eeeb9d.png)
