### ISSUE TITLE
It is not possible to specify additional Directory

### ISSUE THREAD

**Issue by SarahLourenco** [GeneralBots/BotServer#92]
It is not possible to specify additional Directory in function IsDirectory();

https://github.com/GeneralBots/BotServer/blob/528e0a90eb86aeaa28121ac17d2534487d0c54fc/packages/core.gbapp/services/GBDeployer.ts#L99

**Comment by rodrigorodriguez** [comment]
Currently just one folder is allowed, BotBook updated at: https://github.com/GeneralBots/BotBook/blob/master/book/chapter-07-administration.md#enviroment-variables-reference
